name: Build

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - README.md

  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - README.md    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-scala
        path: | 
          ~/.ivy2/cache
          ~/.sbt
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Compile and run tests
      run: sbt ";clean ;+test"